#line 2 "front/lex.yy.c"

#line 4 "front/lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 106
#define YY_END_OF_BUFFER 107
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[316] =
    {   0,
        0,    0,  107,  105,    3,    4,   79,  105,   61,   70,
      105,   95,   96,   59,   57,   98,   58,   99,   60,  102,
       97,   67,   80,   66,  104,  104,   93,   94,   72,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,   91,   71,   92,   73,    3,   65,
        0,  101,   85,   77,   88,    0,   83,   62,   81,   63,
      102,   82,  103,    0,    0,   84,  103,  102,   74,   69,
       64,   68,   75,  104,  104,   89,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,   21,  104,  104,  104,
      104,  104,  104,  104,   23,  104,  104,  104,  104,  104,

      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,   90,   78,  100,    0,    0,
        0,    2,  103,   86,   87,   76,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,   25,  104,  104,   44,  104,
      104,   13,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,   30,  104,  104,
      104,  104,    1,  104,  104,  104,  104,  104,   40,   28,
      104,   41,  104,  104,  104,  104,   24,   49,  104,  104,
      104,  104,  104,  104,  104,  104,   45,  104,   54,  104,

      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
       56,  104,  104,   52,   47,  104,  104,  104,  104,  104,
      104,   18,   31,   50,  104,  104,  104,  104,   53,   10,
       43,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,   46,  104,  104,   55,  104,  104,   33,  104,  104,
       22,   48,  104,   35,  104,  104,  104,   42,  104,  104,
      104,   37,  104,  104,   12,  104,  104,  104,    7,   20,
       14,  104,   27,  104,   34,  104,  104,  104,   39,  104,
       29,    9,   32,  104,  104,  104,   38,    5,  104,  104,
      104,  104,  104,    8,   19,  104,  104,  104,  104,   15,

      104,  104,   17,  104,  104,   51,    6,  104,   16,   11,
       26,  104,  104,   36,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,    1,   18,   19,
       20,   21,    1,    1,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   23,   22,   22,   22,   22,   22,   22,   22,
       24,    1,   25,   26,   27,    1,   28,   29,   30,   31,

       32,   33,   34,   35,   36,   22,   37,   38,   39,   40,
       41,   42,   22,   43,   44,   45,   46,   47,   48,   49,
       50,   51,   52,   53,   54,   55,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[56] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    1,    1,    1,
        1,    3,    3,    1,    1,    1,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[321] =
    {   0,
        0,    0,  340,  341,  337,  341,  318,  332,  316,   49,
        0,  341,  341,  315,   45,  341,   44,  317,   51,   51,
      341,   40,  313,   52,    0,  287,  341,  341,  311,   34,
       33,   47,   38,   46,   53,   57,  289,   70,   64,  297,
       58,   66,  287,  292,  341,   60,  341,  341,  324,  341,
      320,  319,  341,  341,  341,  315,  341,  341,  341,  341,
      305,  341,  304,  309,  316,  341,  301,  100,  297,  341,
      341,  341,   79,    0,  273,  341,  271,  270,  272,  280,
      266,   74,  282,  281,  268,  274,  260,  261,  258,  258,
      264,  261,  259,  256,    0,  256,   76,  257,  251,  247,

      256,  263,   86,  263,  246,  249,   83,  247,  252,  247,
       87,   86,  243,   93,  249,  341,  341,  341,  273,  117,
      280,  341,  265,  341,  341,  341,  245,  235,  247,  240,
      249,  244,  243,  244,  230,  228,  226,  242,  240,  236,
      228,  234,  221,  236,  235,    0,   94,  217,  229,  226,
      223,    0,  220,  220,  209,  210,  216,  207,  209,  206,
      214,  217,  203,  217,  202,  204,  204,    0,  211,  211,
      213,  202,  228,  198,  194,  193,  203,  197,    0,    0,
      198,    0,  188,  195,  184,  191,    0,    0,  188,  195,
      188,  180,  192,  180,  194,  178,    0,  173,    0,  191,

      190,  185,  180,  172,  169,  177,  182,  168,  180,  174,
        0,  160,  163,    0,    0,  161,  173,  170,  175,  157,
      173,    0,    0,    0,  160,  161,  166,  166,    0,  158,
        0,  156,  149,  153,  159,  159,  156,  144,  158,  157,
      146,    0,  155,  139,    0,  148,  139,  137,  144,  143,
        0,    0,  148,    0,  137,  130,  130,    0,  130,  123,
      140,    0,  141,  142,    0,  137,  136,  122,    0,    0,
        0,  133,    0,  124,    0,  132,  125,  117,    0,  129,
        0,    0,    0,  120,  127,  128,    0,    0,  125,  114,
      115,  114,  121,    0,    0,  107,  110,  118,  118,    0,

      105,   93,    0,   90,   92,    0,    0,   73,    0,    0,
        0,   73,   56,    0,  341,  136,  139,   74,  142,  145
    } ;

static const flex_int16_t yy_def[321] =
    {   0,
      315,    1,  315,  315,  315,  315,  315,  316,  315,  315,
      317,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  318,  318,  315,  315,  315,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  315,  315,  315,  315,  315,  315,
      316,  316,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  319,  320,  315,  315,  315,  315,  315,
      315,  315,  315,  318,  318,  315,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,

      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  315,  315,  315,  319,  319,
      320,  315,  315,  315,  315,  315,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  319,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,

      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,

      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,    0,  315,  315,  315,  315,  315
    } ;

static const flex_int16_t yy_nxt[397] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   25,   30,   31,   32,
       33,   34,   35,   25,   25,   36,   25,   37,   25,   38,
       25,   39,   40,   41,   42,   25,   43,   44,   25,   25,
       25,   45,   46,   47,   48,   54,   58,   60,   69,   70,
       61,   64,   77,   62,   59,   67,   65,   68,   55,   86,
       66,   72,   73,   79,   82,   80,   74,   78,   87,  116,
       91,   83,   81,   88,   84,   89,  314,   85,   92,   95,
       93,  102,  106,   94,   90,   96,   97,   99,  125,  126,

      111,  100,  107,  108,  313,  109,  103,  110,  112,  104,
      160,  113,  117,  167,   67,  101,   68,  133,  134,  148,
      149,  155,  165,  312,  311,  161,  156,  120,  170,  166,
      171,  193,  173,  310,  194,  168,   51,  309,   51,   56,
      308,   56,  119,  119,  119,  121,  121,  121,  307,  306,
      305,  304,  303,  302,  301,  300,  299,  298,  297,  296,
      295,  294,  293,  292,  291,  290,  289,  288,  287,  286,
      285,  284,  283,  282,  281,  280,  279,  278,  277,  276,
      275,  274,  273,  272,  271,  270,  269,  268,  267,  266,
      265,  264,  263,  262,  261,  260,  259,  258,  257,  256,

      255,  254,  253,  252,  251,  250,  249,  248,  247,  246,
      245,  244,  243,  242,  241,  240,  239,  238,  237,  236,
      235,  234,  233,  232,  231,  230,  229,  228,  227,  226,
      225,  224,  223,  222,  221,  220,  219,  218,  120,  217,
      216,  215,  214,  213,  212,  211,  210,  209,  208,  207,
      206,  205,  204,  203,  202,  201,  200,  199,  198,  197,
      196,  195,  192,  191,  190,  189,  188,  187,  186,  185,
      184,  183,  182,  181,  180,  179,  178,  177,  176,  175,
      174,  123,  122,  120,  172,  169,  164,  163,  162,  159,
      158,  157,  154,  153,  152,  151,  150,  147,  146,  145,

      144,  143,  142,  141,  140,  139,  138,  137,  136,  135,
      132,  131,  130,  129,  128,  127,  124,  123,  122,  120,
       63,   61,  118,   52,   52,   49,  115,  114,  105,   98,
       76,   75,   71,   63,   57,   53,   52,   50,   49,  315,
        3,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315

    } ;

static const flex_int16_t yy_chk[397] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   10,   15,   17,   22,   22,
       17,   19,   30,   17,   15,   20,   19,   20,   10,   33,
       19,   24,   24,   31,   32,   31,  318,   30,   33,   46,
       35,   32,   31,   34,   32,   34,  313,   32,   35,   36,
       35,   39,   41,   35,   34,   36,   36,   38,   73,   73,

       42,   38,   41,   41,  312,   41,   39,   41,   42,   39,
      107,   42,   46,  112,   68,   38,   68,   82,   82,   97,
       97,  103,  111,  308,  305,  107,  103,  120,  114,  111,
      114,  147,  120,  304,  147,  112,  316,  302,  316,  317,
      301,  317,  319,  319,  319,  320,  320,  320,  299,  298,
      297,  296,  293,  292,  291,  290,  289,  286,  285,  284,
      280,  278,  277,  276,  274,  272,  268,  267,  266,  264,
      263,  261,  260,  259,  257,  256,  255,  253,  250,  249,
      248,  247,  246,  244,  243,  241,  240,  239,  238,  237,
      236,  235,  234,  233,  232,  230,  228,  227,  226,  225,

      221,  220,  219,  218,  217,  216,  213,  212,  210,  209,
      208,  207,  206,  205,  204,  203,  202,  201,  200,  198,
      196,  195,  194,  193,  192,  191,  190,  189,  186,  185,
      184,  183,  181,  178,  177,  176,  175,  174,  173,  172,
      171,  170,  169,  167,  166,  165,  164,  163,  162,  161,
      160,  159,  158,  157,  156,  155,  154,  153,  151,  150,
      149,  148,  145,  144,  143,  142,  141,  140,  139,  138,
      137,  136,  135,  134,  133,  132,  131,  130,  129,  128,
      127,  123,  121,  119,  115,  113,  110,  109,  108,  106,
      105,  104,  102,  101,  100,   99,   98,   96,   94,   93,

       92,   91,   90,   89,   88,   87,   86,   85,   84,   83,
       81,   80,   79,   78,   77,   75,   69,   67,   65,   64,
       63,   61,   56,   52,   51,   49,   44,   43,   40,   37,
       29,   26,   23,   18,   14,    9,    8,    7,    5,    3,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "front/java.l"
#line 2 "front/java.l"
    #include <string.h>
	#include <stdlib.h>
	#include <stdio.h>
	#include "tool/tree.h"//因为下部分依赖此，因此置于前
	#include "java.tab.h"//这里的yylval类型定义很不稳定...在java.y中未定义时这里就可能先定义成int了。因此直接定义为union
	
	
    int line = 1;

	

	int symbolnum=0;
	int floatnum=0;
	int intnum=0;
	int stringnum=0;
	int charnum=0;
	
	pNode savesymbol();
	pNode savechars();
	pNode saveIntegers();
	pNode savefloats();
	pNode savestrings();
	pNode doyylval(int type);
	
#line 660 "front/lex.yy.c"
/*正则优先级：()[] >  *+?  个数 >  字符连接  >  |
转义有俩种方式："xxx"或者\x  ""内的内容作为字符匹配*/
#line 663 "front/lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 53 "front/java.l"

#line 882 "front/lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 316 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 341 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 54 "front/java.l"
{/* skip */}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 55 "front/java.l"
{/* skip */}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 56 "front/java.l"
{/* skip */}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 57 "front/java.l"
{line++;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 58 "front/java.l"
{yylval.pnode = doyylval(_PRIVATE);  return _PRIVATE;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 59 "front/java.l"
{yylval.pnode = doyylval(_PROTECTED);  return _PROTECTED;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 60 "front/java.l"
{yylval.pnode = doyylval(_PUBLIC);  return _PUBLIC;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 61 "front/java.l"
{yylval.pnode = doyylval(_ABSTRACT);  return _ABSTRACT;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 62 "front/java.l"
{yylval.pnode = doyylval(_EXTENDS);  return _EXTENDS;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 63 "front/java.l"
{yylval.pnode = doyylval(_FINAL);  return _FINAL;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 64 "front/java.l"
{yylval.pnode = doyylval(_IMPLEMENTS);  return _IMPLEMENTS;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 65 "front/java.l"
{yylval.pnode = doyylval(_NATIVE);  return _NATIVE;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 66 "front/java.l"
{yylval.pnode = doyylval(_NEW);  return _NEW;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 67 "front/java.l"
{yylval.pnode = doyylval(_STATIC);  return _STATIC;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 68 "front/java.l"
{yylval.pnode = doyylval(_STRICTFP);  return _STRICTFP;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 69 "front/java.l"
{yylval.pnode = doyylval(_TRANSIENT);  return _TRANSIENT;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 70 "front/java.l"
{yylval.pnode = doyylval(_VOLATILE);  return _VOLATILE;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 72 "front/java.l"
{yylval.pnode = doyylval(_BREAK);  return _BREAK;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 73 "front/java.l"
{yylval.pnode = doyylval(_CONTINUE);  return _CONTINUE;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 74 "front/java.l"
{yylval.pnode = doyylval(_RETURN);  return _RETURN;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 75 "front/java.l"
{yylval.pnode = doyylval(_DO);  return _DO;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 76 "front/java.l"
{yylval.pnode = doyylval(_WHILE);  return _WHILE;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 77 "front/java.l"
{yylval.pnode = doyylval(_IF);  return _IF;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 78 "front/java.l"
{yylval.pnode = doyylval(_ELSE);  return _ELSE;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 79 "front/java.l"
{yylval.pnode = doyylval(_FOR);  return _FOR;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 80 "front/java.l"
{yylval.pnode = doyylval(_INSTANCEOF);  return _INSTANCEOF;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 81 "front/java.l"
{yylval.pnode = doyylval(_SWITCH);  return _SWITCH;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 82 "front/java.l"
{yylval.pnode = doyylval(_CASE);  return _CASE;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 83 "front/java.l"
{yylval.pnode = doyylval(_DEFAULT);  return _DEFAULT;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 84 "front/java.l"
{yylval.pnode = doyylval(_TRY);  return _TRY;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 85 "front/java.l"
{yylval.pnode = doyylval(_CATCH);  return _CATCH;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 86 "front/java.l"
{yylval.pnode = doyylval(_FINALLY);  return _FINALLY;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 87 "front/java.l"
{yylval.pnode = doyylval(_THROW);  return _THROW;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 88 "front/java.l"
{yylval.pnode = doyylval(_THROWS);  return _THROWS;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 89 "front/java.l"
{yylval.pnode = doyylval(_ASSERT);  return _ASSERT;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 90 "front/java.l"
{yylval.pnode = doyylval(_SYNCHRONIZED);  return _SYNCHRONIZED;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 92 "front/java.l"
{yylval.pnode = doyylval(_IMPORT);  return _IMPORT;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 93 "front/java.l"
{yylval.pnode = doyylval(_PACKAGE);  return _PACKAGE;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 95 "front/java.l"
{yylval.pnode = doyylval(_BOOLEAN);  return _BOOLEAN;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 96 "front/java.l"
{yylval.pnode = doyylval(_BYTE);  return _BYTE;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 97 "front/java.l"
{yylval.pnode = doyylval(_CHAR);  return _CHAR;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 98 "front/java.l"
{yylval.pnode = doyylval(_DOUBLE);  return _DOUBLE;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 99 "front/java.l"
{yylval.pnode = doyylval(_FLOAT);  return _FLOAT;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 100 "front/java.l"
{yylval.pnode = doyylval(_INT);  return _INT;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 101 "front/java.l"
{yylval.pnode = doyylval(_LONG);  return _LONG;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 102 "front/java.l"
{yylval.pnode = doyylval(_SHORT);  return _SHORT;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 103 "front/java.l"
{yylval.pnode = doyylval(_VOID);  return _VOID;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 104 "front/java.l"
{yylval.pnode = doyylval(_STRING);  return _STRING;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 105 "front/java.l"
{yylval.pnode = doyylval(_ENUM);  return _ENUM;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 106 "front/java.l"
{yylval.pnode = doyylval(_CLASS);  return _CLASS;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 107 "front/java.l"
{yylval.pnode = doyylval(_INTERFACE);  return _INTERFACE;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 109 "front/java.l"
{yylval.pnode = doyylval(_TRUE);  return _TRUE;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 110 "front/java.l"
{yylval.pnode = doyylval(_FALSE);  return _FALSE;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 111 "front/java.l"
{yylval.pnode = doyylval(_NUL);  return _NUL;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 112 "front/java.l"
{yylval.pnode = doyylval(_SUPER);  return _SUPER;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 113 "front/java.l"
{yylval.pnode = doyylval(_THIS);  return _THIS;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 115 "front/java.l"
{yylval.pnode = doyylval(_ADD);  return _ADD;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 116 "front/java.l"
{yylval.pnode = doyylval(_SUB);  return _SUB;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 117 "front/java.l"
{yylval.pnode = doyylval(_MUL);  return _MUL;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 118 "front/java.l"
{yylval.pnode = doyylval(_DIV);  return _DIV;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 119 "front/java.l"
{yylval.pnode = doyylval(_MOD);  return _MOD;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 120 "front/java.l"
{yylval.pnode = doyylval(_ADD2);  return _ADD2;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 121 "front/java.l"
{yylval.pnode = doyylval(_SUB2);  return _SUB2;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 123 "front/java.l"
{yylval.pnode = doyylval(_CMP);  return _CMP;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 124 "front/java.l"
{yylval.pnode = doyylval(_NCMP);  return _NCMP;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 125 "front/java.l"
{yylval.pnode = doyylval(_MORE);  return _MORE;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 126 "front/java.l"
{yylval.pnode = doyylval(_LESS);  return _LESS;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 127 "front/java.l"
{yylval.pnode = doyylval(_MCMP);  return _MCMP;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 128 "front/java.l"
{yylval.pnode = doyylval(_LCMP);  return _LCMP;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 130 "front/java.l"
{yylval.pnode = doyylval(_AND);  return _AND;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 131 "front/java.l"
{yylval.pnode = doyylval(_OR);  return _OR;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 132 "front/java.l"
{yylval.pnode = doyylval(_XOR);  return _XOR;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 133 "front/java.l"
{yylval.pnode = doyylval(_NOT);  return _NOT;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 134 "front/java.l"
{yylval.pnode = doyylval(_SHL);  return _SHL;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 135 "front/java.l"
{yylval.pnode = doyylval(_SHR);  return _SHR;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 136 "front/java.l"
{yylval.pnode = doyylval(_SAR);  return _SAR;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 138 "front/java.l"
{yylval.pnode = doyylval(_BAND);  return _BAND;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 139 "front/java.l"
{yylval.pnode = doyylval(_BOR);  return _BOR;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 140 "front/java.l"
{yylval.pnode = doyylval(_BNOT);  return _BNOT;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 142 "front/java.l"
{yylval.pnode = doyylval(_MOV);  return _MOV;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 143 "front/java.l"
{yylval.pnode = doyylval(_ADDMOV);  return _ADDMOV;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 144 "front/java.l"
{yylval.pnode = doyylval(_SUBMOV);  return _SUBMOV;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 145 "front/java.l"
{yylval.pnode = doyylval(_MULMOV);  return _MULMOV;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 146 "front/java.l"
{yylval.pnode = doyylval(_DIVMOV);  return _DIVMOV;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 147 "front/java.l"
{yylval.pnode = doyylval(_MODMOV);  return _MODMOV;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 148 "front/java.l"
{yylval.pnode = doyylval(_SHLMOV);  return _SHLMOV;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 149 "front/java.l"
{yylval.pnode = doyylval(_SHRMOV);  return _SHRMOV;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 150 "front/java.l"
{yylval.pnode = doyylval(_ANDMOV);  return _ANDMOV;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 151 "front/java.l"
{yylval.pnode = doyylval(_XORMOV);  return _XORMOV;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 152 "front/java.l"
{yylval.pnode = doyylval(_ORMOV);  return _ORMOV;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 154 "front/java.l"
{yylval.pnode = doyylval(_LBRACE);  return _LBRACE;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 155 "front/java.l"
{yylval.pnode = doyylval(_RBRACE);  return _RBRACE;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 156 "front/java.l"
{yylval.pnode = doyylval(_LBRACKET);  return _LBRACKET;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 157 "front/java.l"
{yylval.pnode = doyylval(_RBRACKET);  return _RBRACKET;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 158 "front/java.l"
{yylval.pnode = doyylval(_LPARENTHESE);  return _LPARENTHESE;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 159 "front/java.l"
{yylval.pnode = doyylval(_RPARENTHESE);  return _RPARENTHESE;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 160 "front/java.l"
{yylval.pnode = doyylval(_SEMICOLON);  return _SEMICOLON;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 161 "front/java.l"
{yylval.pnode = doyylval(_COMMA);  return _COMMA;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 162 "front/java.l"
{yylval.pnode = doyylval(_POINT);  return _POINT;}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 164 "front/java.l"
{yylval.pnode = savechars();  return _CUSTCHAR;}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 165 "front/java.l"
{yylval.pnode = savestrings();  return _CUSTSTRING;}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 166 "front/java.l"
{yylval.pnode = saveIntegers();  return _CUSTINT;}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 167 "front/java.l"
{yylval.pnode = savefloats();  return _CUSTFLOAT;}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 170 "front/java.l"
{yylval.pnode = savesymbol();  return _SYMBOL;}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 173 "front/java.l"
{printf("Unrecognized symbol:%s in %d \n",yytext,line);}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 176 "front/java.l"
ECHO;
	YY_BREAK
#line 1472 "front/lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 316 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 316 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 315);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 176 "front/java.l"


pNode doyylval(int type){
	
	pNode ls=MakeNodeNoAttSub(type,strdup(yytext));
		printf("  %p  ;",ls);
	return ls;
	
}


pNode savesymbol()
{
	
	symbolnum++;
	return MakeNodeNoAttSub(_SYMBOL,strdup(yytext));
}

pNode savechars()
{
	
	charnum++;
	return MakeNodeNoAttSub(_CUSTCHAR,strdup(yytext));
	
}
pNode savestrings()
{

	stringnum++;
	return MakeNodeNoAttSub(_CUSTSTRING,strdup(yytext));
}

pNode saveIntegers()
{
	
	intnum++;
	return MakeNodeNoAttSub(_CUSTINT,strdup(yytext));
}
pNode savefloats()
{

	floatnum++;
	return MakeNodeNoAttSub(_CUSTFLOAT,strdup(yytext));
}

//返回1停止lex解析，这里只解析一个文件，针对class
int yywrap() {
    printf("Over-------------\n");
    return 1;
}












